config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  resources :dishes
  resources :meals

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @dish = Dish.new
  end

  def create
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
  end

  def create
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/dishes/new.html.erb
<div class="container">
  <%= form_for @dish  do |f| %>
    <div class="form-group">
      <label for="">Name</label>
      <input type="text" name="dish[name]" id="dish_name" class="form-control">
    </div>
    <div class="form-group">
      <label for="user_last_name">Price</label>
      <input type="text" name="dish[name]" id="dish_price" class="form-control">    </div>
    <div class="form-group">
      <label for="user_password">Restaurant</label>
      <input type="text" name="dish[name]" id="dish_restaurant" class="form-control">    </div>
    </div>
    <button type="submit" class="btn btn-success center-block">Submit</button>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <a class="navbar-brand" href="<%= root_path %>">FoodBook</a>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= new_dish_path %>">New Dish</a></li>
            <li><a href="<%= new_meal_path %>">New Meal</a></li>
        </ul>
       </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/meals/create.html.erb
<h1>Meals#create</h1>
<p>Find me in app/views/meals/create.html.erb</p>

app/views/meals/new.html.erb
<div class="container">
  <%= form_for @meal  do |f| %>
    <div class="form-group">
      <label for="">Name</label>
      <input type="text" name="meal[name]" id="meal_name" class="form-control">
    </div>
    <div class="form-group">
      <label for="user_last_name">Price</label>
      <input type="text" name="meal[name]" id="meal_price" class="form-control">    </div>
    <div class="form-group">
      <label for="user_password">Restaurant</label>
      <input type="text" name="meal[name]" id="meal_restaurant" class="form-control">    </div>
      <div class="form-group">
        <label for="user_password">City</label>
        <input type="text" name="meal[name]" id="meal_city" class="form-control">    </div>
    </div>
    <button type="submit" class="btn btn-success center-block">Submit</button>
  <% end %>

</div>

app/views/static_pages/index.html.erb
<h1 class="text-center">Que onda putos</h1>
<p class="text-center">Agreguen sus melonas</p>